name: Deploy Frontend to GitHub Pages

on:
  push:
    branches: [ main ] # Se ejecuta al hacer push a la rama main

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: 'pages'
  cancel-in-progress: true

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 11.1.3

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --no-frozen-lockfile

      - name: Build frontend
        env:
          VITE_API_URL: https://gustitos-y-cafecitos.onrender.com/api
        run: pnpm --filter web build

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './apps/web/dist' # O la carpeta de salida de tu build (dist, build, out, etc.)

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
